### ISSUE TITLE
Replace data matrix with something faster

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_social#7]
e.g. @gestom's circle features.

**Comment by Jailander** [comment]
yes I'll talk with @gestom for this shouldn't be a big issue

**Comment by cdondrup** [comment]
How is the false positive rate of this when only detecting one circle? Because we don't want to tweet a lot of useless images.

**Comment by Jailander** [comment]
No, there are to ideas, one is to have a QR code or datamatrix delimited by circles so we can cut the image and then the reader is quite fast when it doesn't have to look for the code on a big image, the second option is to use a specific combination of circles like the robot station label

**Comment by cdondrup** [comment]
How big do the circles have to be to be detected? We don't want people holding A4 sheets into the camera

**Comment by Jailander** [comment]
I think they have to be 24 pixels wide in the image

**Comment by mzillich** [comment]
How about AR Toolkit markers
http://studierstube.icg.tugraz.at/handheld_ar/artoolkitplus.php
we have that as ROS modules:
https://github.com/v4r-tuwien/v4r_ros/tree/v4r-devel/v4r_artoolkitplus

**Comment by gestom** [comment]
I will have a look at it. However, I tested the AR Toolkit (as part of the ARUco system) some tome ago and it seemed to me that it needs to be at least 25 pixels wide in order to be detected reliably. We did a quick test with SIFT-based matching, which seems to work OK with 18-pixels patterns. The circle detector works  with 12 pixel-wide circles. Given that the card pattern is 5 cm wide, this corresponds to ranges of 1m, 1.5m and 2.2m. If 1.5m is sufficient, then I would prefer the SIFT-based solution, because that is robust to occlusions (people often hold the cards in a way that part of the pattern is occluded)  and would allow us to use a any kind of pattern (e.g. a "Tweet me" label ) on the card.

**Comment by cdondrup** [comment]
See #24

**Comment by marc-hanheide** [comment]
so, close?

**Comment by Jailander** [comment]
I would say so, even though we did not replace we "created an alternative" :)

**Comment by cdondrup** [comment]
Haven't seen it in action yet. So can't say if it's better or not.

**Comment by cdondrup** [comment]
Seen it now. Works brilliantly.
